### ISSUE TITLE
Can't adjust the 3 mutation type probabilities independently.

### ISSUE THREAD

**Issue by PhoneixS** [MaxRobinsonTheGreat/LifeEngine#19]
**Describe the bug**
When you try to adjust the 3 mutation type probabilities independently, when you edit one of the inputs the other adjust to the left value so you always have one distinct value, and the rest is divided by the other two (so they are equal).

**To Reproduce**

1. Go to Simulation controls.
2. Edit a value of Mutation Type Probabilities.
3. Edit another different value of Mutation Type Probabilities.
4. The first value is changed automatically to the same value as the third.

**Expected behavior**
The first value is left as it is and only the third value is adjusted.

**Environment:**
 - Desktop
 - Linux
 - Firefox

**Comment by MaxRobinsonTheGreat** [comment]
This is expected behavior, the probs must add up to 100 and need to be balanced. Its not very intuitive, but how else could it work? 
In truth I am planning on removing this from the sim controls, it adds little and takes up valuable ui space.

**Comment by PhoneixS** [comment]
You can adjust only the last/third used. For example:

1. Start with 33% 33% 33%.
2. Change one to 20%, adjust the other two (`(100-20)/2`): 20% 40% 40%
3. Change one of the two left to 10%, set the remainded in the third (`100-20-10`): 20% 10% 70%
4. if the third also changes (50%), put the rest into the last modified: 40% 10% 50%

I think you could implement it having a list of the inputs sorted by the last edited, so when the user change one you put it at the to the front of the list, and adjust the total with the third (if it isn't enough, for example when the edit set a 100%, use the second too).

**Comment by PhoneixS** [comment]
I have implemented a possible solution in the pull request which has into consideration the last edited input.

You can also simplify the logic by just having a predefined order, for example, you always have to edit the add input first, then the change input (limited by the remainder of `100 - addProb`) and you can't change the remove input as it is calculated to the remainder of `100 - add - change` clipped to 0.

**Comment by syspic** [comment]
> This is expected behavior, the probs must add up to 100 and need to be balanced. Its not very intuitive, but how else could it work? In truth I am planning on removing this from the sim controls, it adds little and takes up valuable ui space.

Hey! This is a super cool project! I am wondering why you think it adds little value?

I think it's really cool to play around with those values. I have a proposal: 

- Save space by having a button that says "set probabilities" or something better
- when clicked, it opens up a popup (not a popup but i dont know the right word for this. like one of those windows) that has all 3 values
- allow the user to put in any combo of values. Then press ok. 
- if it doesnt add to 100, dont quit and have an error that tells the user to make sure it adds up to 100

This way I can set values like 20,45,35. If i try to do that right now, it doesnt work since the other two automatically update

**Comment by xkortex** [comment]
I also think it's pretty valuable to be able to adjust the probabilities of mutations, and was initially confused by the "whack a mole" nature of the UI. Not sure I'm sold on the "free entry and validate the sum" UI, either, I envision a 3 axis selector similar to RGB/HSV color selectors. 

Though, I'm not sure why the probabilities of each need to add to 100%. Like, why does this have to be an elif switch of mutually exclusive events? Can't we just roll for each event independently, and then add/change/delete independently? 

https://github.com/MaxRobinsonTheGreat/LifeEngine/blob/2ef721682a1086d6659a6865bf2bef8fef25c0d5/src/Organism/Organism.js#L128

**Comment by MaxRobinsonTheGreat** [comment]
UPDATE: I am no longer planning on removing the feature and will improve the ui.

@xkortex Excellent suggestion, not sure why I didn't think of this. I've been wracking my brain for an intuitive way to balance the probs, but the balance is unnecessary and they can be independent mutations. Will implement.

And your point about species is a separate issue, my solution is a "good enough for now" implementation since species aren't actually used for anything other than statistics. If you'd like to continue the conversation about this, open a discussion in the the discussion tab. 

Thanks all

**Comment by syspic** [comment]
@xkortex Thanks for the writeup! I am not familar with JS/UI/UX/webdesign so this was really helpful! Thank you! 

And thanks @MaxRobinsonTheGreat  for listening to the community feedback! It's super cool and encouraging to know that you are interested in what we have to say!

**Comment by xkortex** [comment]
@MaxRobinsonTheGreat I think it actually dovetails with [the discussion about state](https://github.com/MaxRobinsonTheGreat/LifeEngine/discussions/38). 

I really think a "static genes datastructure" based approach would really pay dividends, so I'm really curious what your thoughts are on that.  Just pushed some code so you have something more concrete to look at.
